name: Build Schedule App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install pandas openpyxl

    - name: Build executable for schedule_app.py
      run: pyinstaller --onefile schedule_app.py

    - name: Upload schedule_app artifact
      uses: actions/upload-artifact@v4  # 升级到 v4 版本
      with:
        name: schedule_app_${{ matrix.os }}
        path: dist/schedule_app.exe  # 对于 macOS 会是 dist/schedule_app，Windows 是 .exe

    - name: Build executable for schedule_2025_h1.py
      run: pyinstaller --onefile schedule_2025_h1.py

    - name: Upload schedule_2025_h1 artifact
      uses: actions/upload-artifact@v4  # 升级到 v4 版本
      with:
        name: schedule_2025_h1_${{ matrix.os }}
        path: dist/schedule_2025_h1.exe  # 对于 macOS 会是 dist/schedule_2025_h1，Windows 是 .exe