name: Build Schedule App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install pandas openpyxl

    - name: Build executable
      run: pyinstaller --onefile schedule_app.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: schedule_app
        path: dist/
